name: 🌍 OSCA Event Request
description: Submit a request to host an Open Source Community Africa chapter event.
title: "[Event Request]: <Event Name> - <Country>"
labels: ["event", "request"]
assignees: []
projects: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📅 Event Information
        Please fill in all applicable details for your upcoming OSCA chapter event.

  - type: input
    id: event-name
    attributes:
      label: Event Name
      placeholder: e.g. OSCA Dar es Salaam Hackathon 2025
    validations:
      required: true

  - type: textarea
    id: event-description
    attributes:
      label: Event Description
      description: Provide a clear summary of your event, including format and goal.
    validations:
      required: true

  - type: input
    id: event-date
    attributes:
      label: Event Date
      placeholder: dd/mm/yyyy
    validations:
      required: true

  - type: input
    id: event-time
    attributes:
      label: Event Time
      placeholder: e.g. 10:00 AM (EAT)
    validations:
      required: true

  - type: input
    id: event-duration
    attributes:
      label: Event Duration
      placeholder: e.g. 4 hours
    validations:
      required: true

  - type: input
    id: event-location
    attributes:
      label: Event Location
      placeholder: e.g. University of Dar es Salaam, CoICT Auditorium
    validations:
      required: true

  - type: input
    id: estimated-attendees
    attributes:
      label: Estimated Number of Attendees
      description: Refer to OSCA's [event groups](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/event-budget.md#event-groups)
      placeholder: e.g. 50 - OSCA Event Group A
    validations:
      required: true

  - type: input
    id: rsvp-link
    attributes:
      label: Event RSVP Link
      placeholder: https://example.com/rsvp
    validations:
      required: true

  - type: textarea
    id: chapter-benefit
    attributes:
      label: How does this benefit your chapter?
      description: Explain why OSCA should approve this event and how it aligns with your chapter goals.
    validations:
      required: true

  - type: textarea
    id: help-needed
    attributes:
      label: What help do you need with this event?
      description: Let us know how OSCA can support this event (e.g. swag, promotion, budget).
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## ✅ Pre-Submission Checklist
        Confirm you have completed the following before submitting.
        - [Budget template link](https://bit.ly/3SmTFQa)
        - [Request form link](https://bit.ly/osca-cl-request)

  - type: checkboxes
    id: before-submission
    attributes:
      label: Before you post the issue
      options:
        - label: I have followed the issue title format.
        - label: I have applied the correct labels (Country, Type of Event, Requests).
        - label: I have created a budget for my event (if I need sponsorship).
        - label: I have completed the request form (if I need sponsorship).

  - type: checkboxes
    id: before-event
    attributes:
      label: Before the event
      options:
        - label: My event is approved.
        - label: My event's RSVP page has been created.
        - label: For non-Nigerians, I have submitted an expense request on Open Collective using my event title.
        - label: For Nigerians, I am waiting for a bank transfer from the financial manager.
        - label: I have received sponsorship and am ready to go (if applicable).

  - type: checkboxes
    id: after-event
    attributes:
      label: After the event
      options:
        - label: I have completed the post-event report.
        - label: I have submitted all related expense receipts as required.
        - label: This issue is ready to be closed.
